#!/bin/bash

function createDataBase(){
fileName=$1
DataBasePath=/home/eladawy/BashProject/DataBase/*
found=1
  for file in $DataBasePath
     do
      existName=$(basename -- "$file")
      existDbName="${existName%.*}"
      if [[ $fileName == $existDbName ]]
        then 
      	    echo "DataBase Already Exist !"
      	    found=0 
      	    break;
      fi
     done
  if [[ $found != 0 ]]
     then
       mkdir /home/eladawy/BashProject/DataBase/$fileName
       echo "DataBase Created"
  fi
}

export -f createDataBase
