#!/bin/bash
DataBasePath=/home/eladawy/BashProject/DataBase/$1/*
DataBaselocation=/home/eladawy/BashProject/DataBase/$1
function createTables(){
typeset -a colNames
typeset -a colTypes
pk=""
echo "---------------------------------------"
echo "Enter Table Name : "
read tableName
checkTableName $tableName
#echo "$?"  stored immediately after the function call in $?
if [[ $? != 0 ]]
then
    echo "Enter Numbers Of Cloumns: "
    read numCols
    typeset -a colNameType
    echo "ColumnName ColumnType [ Pk must be one 'first pk is token ?' ]"
    for ((i=0;i<$numCols;i++))
      do
        let row=i+1 
        echo "enter Column $row"
        read col_info 
        IFS=' ' read -r -a col_values <<< "$col_info"
        checkColType ${col_values[1]}
        if [[ $? == 1 ]]
          then
            #colNameType[i]=$col_info" "
            colNames[i]=${col_values[0]}"#"
            colTypes[i]=${col_values[1]}"#"
             if [[ ${#col_values[@]} == 3 ]] #get primary key
               then 
                 #pk=${col_values[0]}
                 pk=$i
              fi
        else
          echo "enter valid dataType { int , float , char , string }"
          i=$i-1
       fi 
      done
  touch $DataBaselocation/$tableName
  
     #echo "${colNames[@]}"
     #echo "${colTypes[@]}"
     #echo "$pk"
     
  # first 3 line is reserved for table_info
  printf "%s" "${colNames[@]}" > $DataBaselocation/$tableName
  printf "%s\n" >> $DataBaselocation/$tableName
  printf "%s" "${colTypes[@]}" >> $DataBaselocation/$tableName
  printf "%s\n" >> $DataBaselocation/$tableName
  printf "%s" "$pk" >> $DataBaselocation/$tableName
  printf "%s\n" >> $DataBaselocation/$tableName
  
  echo "Table $tableName created."
fi

}

function checkTableName(){

for file in $DataBasePath
     do
      existName=$(basename -- "$file")
      existTableName="${existName%.*}"
      if [[ $1 == $existTableName ]]
        then
      	    echo "Table $1 Already Exist !"
      	    return 0
      fi
     done

return 1
}

function checkColType(){
case $1 in

  "int")
    return 1
    ;;

  "float")
    return 1
    ;;

  "char")
    return 1
    ;;
   "string")
    return 1
    ;;

  *)
    return 0
    ;;
esac
}



export -f createTables
