#!/bin/bash

function deleteDataBase(){
fileName=$1
DataBasePath=/home/eladawy/BashProject/DataBase/*
found=1
  for file in $DataBasePath
     do
      existName=$(basename -- "$file")
      existDbName="${existName%.*}"
      if [[ $fileName == $existDbName ]]
        then
            rm -r  /home/eladawy/BashProject/DataBase/$fileName
      	    echo "DataBase deleted"
      	    found=0 
      	    break;
      fi
     done
  if [[ $found != 0 ]]
     then
       echo "DataBase Not Found ?"
  fi
}

export -f deleteDataBase
