#!/bin/bash

Path=/home/eladawy/BashProject/HelperFunctions
function editingTables(){
echo "-----------------------------------------"
select choice in ShowTables Create_Table Drop_Table exit
do
case $choice in
ShowTables)
	source $Path/showTables ; showTables $1
	;;
Create_Table)
	source $Path/createTable ; createTables $1
	;;
Drop_Table)
	source $Path/dropTables ; dropTables $1
	;;
exit)
	echo "---------------------------------------"
	echo "1) tablesEditing"
	echo "2) tableDataEditing"	
	echo "3) exit"     
	break
	;;
*)
	echo "$REPLY is not found"
	;;
esac
done
}




export -f editingTables

