#!/bin/bash

DataBasePath=/home/eladawy/BashProject/DataBase/$1/*
DataBaseLocation=/home/eladawy/BashProject/DataBase/$1

function insert(){
  echo "insert"
}
function delete(){
 echo "delete"
}
function update(){
echo "update"
}

export -f insert
export -f delete
export -f update
